repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)

-   repo: local
    hooks:
    -   id: unittest
        name: unittest
        entry: python -m unittest discover
        language: system
        'types': [python]
        args: ["-p '*test.py'"] # Probably this option is absolutely not needed.
        pass_filenames: false
        stages: [commit]
