[tool.poetry]
name = "pyasic-super"
version = "0.1.0"
description = ""
authors = ["UpstreamData <brett@upstreamdata.ca>"]
readme = "README.md"
packages = [
    {include = "pyasic"},
    {include = "pyasic_api"}
]

[tool.poetry.dependencies]
python = "^3.10"
pyasic = { path = "./pyasic/", develop = true }
pyasic_api = { path = "./pyasic_api/", develop = true }
pre-commit = "^2.20.0"
mkdocs = "^1.4.2"
mkdocstrings = "^0.19.0"
isort = "^5.10.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
